2024-11-27 22:13:23,801 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:13:23,802 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:13:23,809 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:13:23,822 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:13:23,829 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:13:23,833 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:21:29,270 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:21:29,271 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:21:29,274 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:21:29,281 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:21:29,288 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:21:29,384 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:25:17,464 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:25:17,465 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:25:17,468 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:25:17,473 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:25:17,480 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:25:17,485 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:28:42,177 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:28:42,178 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:28:42,187 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:28:42,197 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:28:42,210 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:28:42,224 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:31:15,206 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:31:15,207 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:31:15,210 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:31:15,215 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:31:15,223 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:31:15,227 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:33:18,786 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:33:18,786 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:33:18,790 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:33:18,797 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:33:18,803 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:33:18,808 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:36:03,977 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:36:03,978 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:36:03,982 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:36:03,990 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:36:03,998 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:36:04,003 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:37:02,791 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:37:02,793 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:37:02,796 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:37:02,805 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:37:02,807 - data_preprocessing - ERROR - Error during text normalization: name 'nltk' is not defined
2024-11-27 22:37:02,807 - data_preprocessing - ERROR - Failed to complete the data transformation process: name 'nltk' is not defined
2024-11-27 22:39:46,943 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:39:46,944 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:39:46,946 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:39:46,951 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:39:46,960 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:39:46,966 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:43:56,872 - data_preprocessing - DEBUG - Data loaded properly
2024-11-27 22:43:56,873 - data_preprocessing - DEBUG - Starting preprocessing for DataFrame
2024-11-27 22:43:56,877 - data_preprocessing - DEBUG - Target column encoded
2024-11-27 22:43:56,884 - data_preprocessing - DEBUG - Duplicates removed
2024-11-27 22:43:56,890 - data_preprocessing - ERROR - Error during text normalization: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

2024-11-27 22:43:56,894 - data_preprocessing - ERROR - Failed to complete the data transformation process: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - 'C:\\Users\\Yash/nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\Yash\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

